{% set name = "dwave-inspector" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1e2824a3063e8ca7a897dda2dcc557a09bbb0026b8b69a2d2f1408cd4ba4fae5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - orjson >=3.10.0
    - dimod >=0.10.0
    - dwave-cloud-client >=0.12.0,<0.14.0
    - dwave-system >=1.3.0
    - flask >=2.2,<4
    - python >={{ python_min }}
    - numpy
    # Below python 3.10
    - importlib-resources >=3.2.0
    - importlib-metadata >=4.8
  run_constrained:
    - dwave-inspectorapp ==0.3.3

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/dwave-inspector
  summary: D-Wave Problem Inspector tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
