{% set name = "dwave-inspector" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0aac2e54a1ca470de17a749690fef820a52bd335292b65c03a09a44dba38b12d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - orjson >=3.10.0
    - dimod >=0.10.0
    - dwave-cloud-client >=0.12.0,<0.14.0
    - dwave-system >=1.3.0
    - flask >=2.2,<4
    - python >={{ python_min }}
    - numpy
    # Below python 3.10
    - importlib-resources >=3.2.0
    - importlib-metadata >=4.8
  run_constrained:
    - dwave-inspectorapp ==0.3.3

test:
  imports:
    - dwave
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/dwave-inspector
  summary: D-Wave Problem Inspector tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
